# PRACTICAL 1

In [1]:
# Demonstrate Basic Data Types and Variable Assignments

a = 10
b = 25.5
c = "Hello"
d = True
e = [1, 2, 3, 4]
f = (10, 20, 30)
g = {"Name": "sirushtika", "Age": 18}
h = {1, 2, 3, 4}

print("Integer:", a, "Type:", type(a))
print("Float:", b, "Type:", type(b))
print("String:", c, "Type:", type(c))
print("Boolean:", d, "Type:", type(d))
print("List:", e, "Type:", type(e))
print("Tuple:", f, "Type:", type(f))
print("Dictionary:", g, "Type:", type(g))
print("Set:", h, "Type:", type(h))

Integer: 10 Type: <class 'int'>
Float: 25.5 Type: <class 'float'>
String: Hello Type: <class 'str'>
Boolean: True Type: <class 'bool'>
List: [1, 2, 3, 4] Type: <class 'list'>
Tuple: (10, 20, 30) Type: <class 'tuple'>
Dictionary: {'Name': 'sirushtika', 'Age': 18} Type: <class 'dict'>
Set: {1, 2, 3, 4} Type: <class 'set'>


# PRACTICAL 2

In [2]:
# Conditional Statements and Loops

# 1. Check Positive Number (if)
num = int(input("Enter a number: "))
if num > 0:
    print("The number is Positive")

# 2. Check Even or Odd (if-else)
num2 = int(input("Enter another number: "))
if num2 % 2 == 0:
    print("Even Number")
else:
    print("Odd Number")

# 3. Grade using if-elif-else
marks = int(input("Enter student marks: "))
if marks >= 90:
    print("Grade A")
elif marks >= 75:
    print("Grade B")
elif marks >= 50:
    print("Grade C")
else:
    print("Fail")

# 4. Login using nested if-else
username = input("Enter username: ")
password = input("Enter password: ")

if username == "admin":
    if password == "1234":
        print("Login Successful")
    else:
        print("Incorrect Password")
else:
    print("Invalid Username")

# 5. Voting Eligibility (one-line if-else)
age = int(input("Enter your age: "))
print("Eligible to Vote" if age >= 18 else "Not Eligible to Vote")

# 6. For Loop
print("\nFor Loop:")
for i in range(1, 6):
    print(i)

# 7. While Loop
print("\nWhile Loop:")
i = 1
while i <= 5:
    print(i)
    i += 1
# 8. Break Statement
print("\nBreak Statement:")
for i in range(1, 10):
    if i == 5:
        break
    print(i)
# 9. Continue Statement
print("\nContinue Statement:")
for i in range(1, 10):
    if i == 5:
        continue
    print(i)
# 10. Pass Statement
print("\nPass Statement:")
for i in range(1, 6):
    if i == 3:
        pass
    print(i)
# 11. Match-Case Statement
day = int(input("Enter day number (1-7): "))
match day:
    case 1:
        print("Monday")
    case 2:
        print("Tuesday")
    case 3:
        print("Wednesday")
    case 4:
        print("Thursday")
    case 5:
        print("Friday")
    case 6:
        print("Saturday")
    case 7:
        print("Sunday")
    case _:
        print("Invalid Day")

Enter a number:  25


The number is Positive


Enter another number:  14


Even Number


Enter student marks:  92


Grade A


Enter username:  admin
Enter password:  1234


Login Successful


Enter your age:  17


Not Eligible to Vote

For Loop:
1
2
3
4
5

While Loop:
1
2
3
4
5

Break Statement:
1
2
3
4

Continue Statement:
1
2
3
4
6
7
8
9

Pass Statement:
1
2
3
4
5


Enter day number (1-7):  6


Saturday


# PRACTICAL 3

In [7]:
# Practical 3 - User Defined Functions

# 1. No arguments, no return value
def hello():
    print("Hello!")

hello()

# 2. Arguments, no return value
def add(a, b):
    print("Addition =", a + b)

add(10, 20)

# 3. No arguments, with return value
def message():
    return "Welcome"

print(message())

# 4. Arguments, with return value
def multiply(a, b):
    return a * b

print("Product =", multiply(5, 4))

# 5. Default argument
def greet(name="Student"):
    print("Hello", name)

greet()
greet("Sirushtika")

# 6. Keyword arguments
def student(name, age):
    print("Name:", name)
    print("Age:", age)

student(age=18, name="Anu")

# 7. Variable-length arguments
def total(*marks):
    print("Total Marks =", sum(marks))

total(80, 90, 85)

# 8. Lambda function
square = lambda x: x * x
print("Square =", square(6))

# 9. Recursive function
def factorial(n):
    if n == 1:
        return 1
    return n * factorial(n - 1)

print("Factorial =", factorial(5))

# 10. Nested function
def outer():
    print("Outer Function")

    def inner():
        print("Inner Function")

    inner()

outer()

Hello!
Addition = 30
Welcome
Product = 20
Hello Student
Hello Sirushtika
Name: Anu
Age: 18
Total Marks = 255
Square = 36
Factorial = 120
Outer Function
Inner Function


# PRACTICAL 4

In [3]:
# Create a list
nums = [1, 2, 3, 4, 5]

print("Original List:", nums)
print("First Element:", nums[0])
print("Last Element:", nums[-1])

# Append
nums.append(6)
print("After Append:", nums)

# Insert
nums.insert(2, 10)
print("After Insert:", nums)

# Remove
nums.remove(10)
print("After Remove:", nums)

# Length
print("Length:", len(nums))

# Traverse
print("List Elements:")
for i in nums:
    print(i)

# List Comprehension
square = [x*x for x in nums]
even = [x for x in nums if x % 2 == 0]
odd = [x for x in nums if x % 2 != 0]
double = [x*2 for x in nums]

matrix = [[1, 2], [3, 4]]
flat = [x for row in matrix for x in row]

print("Squares:", square)
print("Even:", even)
print("Odd:", odd)
print("Double:", double)
print("Flattened List:", flat)

Original List: [1, 2, 3, 4, 5]
First Element: 1
Last Element: 5
After Append: [1, 2, 3, 4, 5, 6]
After Insert: [1, 2, 10, 3, 4, 5, 6]
After Remove: [1, 2, 3, 4, 5, 6]
Length: 6
List Elements:
1
2
3
4
5
6
Squares: [1, 4, 9, 16, 25, 36]
Even: [2, 4, 6]
Odd: [1, 3, 5]
Double: [2, 4, 6, 8, 10, 12]
Flattened List: [1, 2, 3, 4]


# PRACTICAL 5

In [2]:
# Tuple
t = (10, 20, 30, 40, 20)

print("Tuple:", t)
print("First Element:", t[0])
print("Last Element:", t[-1])
print("Length:", len(t))
print("Slicing:", t[1:4])
print("Count of 20:", t.count(20))
print("Index of 30:", t.index(30))

print("Tuple Elements:")
for i in t:
    print(i)

t2 = (50, 60)
print("Concatenated Tuple:", t + t2)

# Set
s = {1, 2, 3, 4}

print("Original Set:", s)

s.add(5)
print("After Add:", s)

s.remove(2)
print("After Remove:", s)

print("Length:", len(s))

print("Set Elements:")
for i in s:
    print(i)

s2 = {3, 4, 5, 6}

print("Union:", s | s2)
print("Intersection:", s & s2)
print("Difference:", s - s2)
print("Symmetric Difference:", s ^ s2)

Tuple: (10, 20, 30, 40, 20)
First Element: 10
Last Element: 20
Length: 5
Slicing: (20, 30, 40)
Count of 20: 2
Index of 30: 2
Tuple Elements:
10
20
30
40
20
Concatenated Tuple: (10, 20, 30, 40, 20, 50, 60)
Original Set: {1, 2, 3, 4}
After Add: {1, 2, 3, 4, 5}
After Remove: {1, 3, 4, 5}
Length: 4
Set Elements:
1
3
4
5
Union: {1, 3, 4, 5, 6}
Intersection: {3, 4, 5}
Difference: {1}
Symmetric Difference: {1, 6}


# PRACTICAL 6

In [3]:
# Dictionary Operations

student = {
    "Name": "Sirushtika",
    "Age": 18,
    "Course": "BSc DS & AI"
}

print("Original Dictionary:", student)

# Access value
print("Name:", student["Name"])

# Add new key
student["College"] = "SDNB Vaishnav College"

# Update value
student["Age"] = 19

# Remove key
student.pop("Course")

# Length
print("Length:", len(student))

# Keys
print("Keys:", student.keys())

# Values
print("Values:", student.values())

# Items
print("Items:", student.items())

# Traverse dictionary
print("Dictionary:")
for key, value in student.items():
    print(key, ":", value)

# Check key
if "Age" in student:
    print("Age key exists")

# Copy dictionary
copy_student = student.copy()
print("Copied Dictionary:", copy_student)

# Clear another dictionary
d = {"A": 1, "B": 2}
d.clear()
print("Cleared Dictionary:", d)

print("Updated Dictionary:", student)

Original Dictionary: {'Name': 'Sirushtika', 'Age': 18, 'Course': 'BSc DS & AI'}
Name: Sirushtika
Length: 3
Keys: dict_keys(['Name', 'Age', 'College'])
Values: dict_values(['Sirushtika', 19, 'SDNB Vaishnav College'])
Items: dict_items([('Name', 'Sirushtika'), ('Age', 19), ('College', 'SDNB Vaishnav College')])
Dictionary:
Name : Sirushtika
Age : 19
College : SDNB Vaishnav College
Age key exists
Copied Dictionary: {'Name': 'Sirushtika', 'Age': 19, 'College': 'SDNB Vaishnav College'}
Cleared Dictionary: {}
Updated Dictionary: {'Name': 'Sirushtika', 'Age': 19, 'College': 'SDNB Vaishnav College'}


# PRACTICAL 7

In [4]:
# File Handling

# Write to file
file = open("sample.txt", "w")
file.write("Welcome to Python\n")
file.write("File Handling Example\n")
file.close()

# Read file
file = open("sample.txt", "r")
print("File Contents:")
print(file.read())
file.close()

# Append data
file = open("sample.txt", "a")
file.write("This is appended text.\n")
file.close()

# Read updated file
file = open("sample.txt", "r")
print("Updated File Contents:")
print(file.read())
file.close()

File Contents:
Welcome to Python
File Handling Example

Updated File Contents:
Welcome to Python
File Handling Example
This is appended text.



# PRACTICAL 8

In [1]:
# Numpy Array Operations 
import numpy as np 

#Creating Numpy Arrays 
array1 = np. array([10,20,30,40,50,])
array2 = np.array([1,2,3,4,5])
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

# Array Addition
print("\nAddition:")
print(array1 + array2)

#Array Subtraction
print("\nSubtraction:")
print(array1 - array2)

# Array Multiplication
print("\nMultiplication:")
print(array1 * array2)

# Array Division
print("\nDivision:")
print(array1 / array2)

# Indexing
print("\nFirst Element:")
print(array1[0])

# Slicing
print("\nSliced Array:")
print(array1[1:4])

# Reshaping
array3 = np.array([1,2,3,4,5,6])
reshape_array = array3.reshape(2,3)

print("\nReshaped Array:")
print(reshape_array)

print("\nShape:", reshape_array.shape)
print("Dimension:", reshape_array.ndim)
print("Size:", reshape_array.size)

# Aggregation
print("\nSum:", np.sum(array1))
print("Mean:", np.mean(array1))
print("Maximum:", np.max(array1))
print("Minimum:", np.min(array1))

# Universal Functions
print("\nSquare Root:")
print(np.sqrt(array1))

print("\nExponential:")
print(np.exp(array2))

# Sorting
print("\nSorted Array:")
print(np.sort(array1))

# Concatenation
print("\nConcatenated Array:")
print(np.concatenate((array1, array2)))



Array 1:
[10 20 30 40 50]

Array 2:
[1 2 3 4 5]

Addition:
[11 22 33 44 55]

Subtraction:
[ 9 18 27 36 45]

Multiplication:
[ 10  40  90 160 250]

Division:
[10. 10. 10. 10. 10.]

First Element:
10

Sliced Array:
[20 30 40]

Reshaped Array:
[[1 2 3]
 [4 5 6]]

Shape: (2, 3)
Dimension: 2
Size: 6

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10

Square Root:
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]

Exponential:
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

Sorted Array:
[10 20 30 40 50]

Concatenated Array:
[10 20 30 40 50  1  2  3  4  5]


# PRACTICAL 9

In [2]:
# Indexing, Slicing and Reshaping in NumPy
import numpy as np

# Creating NumPy Array
array = np.array([10,20,30,40,50,60])

print("Array:")
print(array)

# Indexing
print("\nFirst Element:")
print(array[0])

# Slicing
print("\nSliced Array:")
print(array[1:5])

# Reshaping
array2 = np.array([1,2,3,4,5,6])
reshape_array = array2.reshape(2,3)

print("\nReshaped Array:")
print(reshape_array)

print("\nShape:", reshape_array.shape)
print("Dimension:", reshape_array.ndim)
print("Size:", reshape_array.size)

# Sum and Mean
print("\nSum:", np.sum(array))
print("Mean:", np.mean(array))

# Sorting
print("\nSorted Array:")
print(np.sort(array))

Array:
[10 20 30 40 50 60]

First Element:
10

Sliced Array:
[20 30 40 50]

Reshaped Array:
[[1 2 3]
 [4 5 6]]

Shape: (2, 3)
Dimension: 2
Size: 6

Sum: 210
Mean: 35.0

Sorted Array:
[10 20 30 40 50 60]


# PRACTICAL 10

In [4]:
# Statistical Functions using NumPy
import numpy as np

# Creating NumPy Array
array = np.array([10,20,30,40,50])

print("Array:")
print(array)

print("\nSum:", np.sum(array))
print("Mean:", np.mean(array))
print("Median:", np.median(array))
print("Standard Deviation:", np.std(array))
print("Variance:", np.var(array))

print("\nMinimum:", np.min(array))
print("Maximum:", np.max(array))

print("\nIndex of Minimum:", np.argmin(array))
print("Index of Maximum:", np.argmax(array))

print("\nRange:", np.max(array)-np.min(array))

print("\n25th Percentile:", np.percentile(array,25))
print("50th Percentile:", np.percentile(array,50))
print("75th Percentile:", np.percentile(array,75))

print("\nCumulative Sum:")
print(np.cumsum(array))

print("\nSorted Array:")
print(np.sort(array))

Array:
[10 20 30 40 50]

Sum: 150
Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0

Minimum: 10
Maximum: 50

Index of Minimum: 0
Index of Maximum: 4

Range: 40

25th Percentile: 20.0
50th Percentile: 30.0
75th Percentile: 40.0

Cumulative Sum:
[ 10  30  60 100 150]

Sorted Array:
[10 20 30 40 50]
